#!/usr/bin/env python3

import sys
import os
import json
import http.client
from urllib.request import urlretrieve
from urllib.parse import urlparse
import shutil

if len(sys.argv) < 2:
  print(f'Usage: {sys.argv[0]} <pipeline_id>')
  sys.exit(1)

pipeline_id = sys.argv[1]

slug = open('project.slug', 'r').read().replace('\n', '')
auth_token = open('auth.token', 'r').read().replace('\n', '')

dir = 'packages'

if os.path.isdir(dir):
  shutil.rmtree(dir)

os.mkdir(dir)
os.chdir(dir)

headers = { 'Circle-Token': auth_token }

conn = http.client.HTTPSConnection('circleci.com')

conn.request('GET', f'/api/v2/pipeline/{pipeline_id}/workflow', headers=headers)
res = conn.getresponse()
workflow_data =  json.loads(res.read())

workflow_id = workflow_data['items'][0]['id']

conn.request('GET', f'/api/v2/workflow/{workflow_id}/job', headers=headers)
res = conn.getresponse()
job_data =  json.loads(res.read())

for job in job_data['items']:
  job_number = job['job_number']

  conn.request('GET', f'/api/v2/project/{slug}/{job_number}/artifacts', headers=headers)
  res = conn.getresponse()
  artifact_data =  json.loads(res.read())

  for artifact in artifact_data['items']:
    url = artifact['url']
    filename = os.path.basename(urlparse(url).path)
    print(f'Downloading {filename}')
    urlretrieve(url, filename)

