#!/bin/bash

set -e

export PATH="$PATH:/home/build/flutter/bin:/home/build/.pub-cache/bin"

git clone --depth 1 --branch stable https://github.com/flutter/flutter

flutter doctor -v

flutter pub global activate flutterpi_tool
