#!/bin/bash

set -e

export PATH="$PATH:/home/build/flutter/bin:/home/build/.pub-cache/bin"

ci_version=$(./package-release/.circleci/version flutter-pi)

[ "${ci_version}" ] || exit

git clone --depth 1 --recursive https://github.com/philseeley/flutter-pi.git

cd flutter-pi

version=$(awk -F '"' '/^project\(flutter-pi/ {print $2}' CMakeLists.txt)

[ "${ci_version}" != "${version}" ] && { echo "Inconsistent versions '${ci_version}' '${version}'"; exit 1; }

./package

mv packages/* /tmp/artifacts
