#!/bin/bash

su - build <<__EOF
echo HOME is $HOME
export PATH="$PATH:$HOME/flutter/bin:$HOME/.pub-cache/bin"

(
  cd boatinstrument
  ./package
  find debian
  mv packages/* /tmp/artifacts
)

(
  cd flutter-pi
  ./package
  mv packages/* /tmp/artifacts
)

__EOF
