#!/bin/bash

set -e

uname -a

export PATH="$PATH:/home/build/flutter/bin:/home/build/.pub-cache/bin"

git clone --depth 1 --branch 3.24.3 https://github.com/flutter/flutter
flutter doctor -v

flutter pub global activate flutterpi_tool

mkdir /tmp/artifacts;

git clone --depth 1 https://github.com/philseeley/boatinstrument.git

git clone --depth 1 --recursive https://github.com/philseeley/flutter-pi.git
