#!/bin/bash

getent passwd build

su build <<__EOF
id
pwd
git clone --depth 1 --branch 3.24.3 https://github.com/flutter/flutter
PATH="$PATH:`pwd`/flutter/bin"
flutter doctor -v
mkdir /tmp/artifacts;
id > /tmp/artifacts/id.txt;
uname -a > /tmp/artifacts/uname.txt;
cp /etc/os-release /tmp/artifacts
__EOF
