#!/bin/bash

set -e

cd /home/build/package-release

while read package current new
do
  if [ "${new}" ]
  then
    echo ${package} ${new}
  else
    echo ${package} ${current}
  fi
done < versions > new-versions

mv new-versions -f versions

cat versions

git config --global user.email "phil.seeley@gmail.com"
git config --global user.name "Phil Seeley (via CI)"

git add versions
git commit -m "Versions updated to\n$(cat versions)"
git push
